# Generated by Django 3.0.8 on 2020-07-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=50)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
